#!/usr/bin/env python3
"""Simulate a predicted FrozenLake path against one dataset sample."""

import argparse
import json
import re
from pathlib import Path

MOVE_PATTERN = re.compile(r"go\s+(left|right|up|down)", re.IGNORECASE)
PATH_PATTERN = re.compile(
    r"go\s+(?:left|right|up|down)(?:\s*(?:->|=>|,|;|\||/|\\)\s*go\s+(?:left|right|up|down))*",
    flags=re.IGNORECASE,
)
ANSWER_PATTERN = re.compile(r"<answer>\s*(.*?)\s*</answer>", flags=re.IGNORECASE | re.DOTALL)
GOAL_PATTERN = re.compile(
    r"(?:goal(?: is| =)?(?: at)?|trying to reach|reach)\s*\((\d+),\s*(\d+)\)",
    re.IGNORECASE,
)
START_PATTERN = re.compile(r"(?:start(?:ing position)?(?: is| =)?|I start at)\s*\((\d+),\s*(\d+)\)", re.IGNORECASE)
HOLES_LINE_PATTERN = re.compile(
    r"holes?(?: I must avoid)?\s*:\s*((?:\(\d+,\s*\d+\)\s*,?\s*)+)",
    re.IGNORECASE,
)
COORD_PATTERN = re.compile(r"\((\d+),\s*(\d+)\)")


def parse_args():
    parser = argparse.ArgumentParser(description="Simulate one predicted path on a FrozenLake sample.")
    parser.add_argument("--dataset-path", required=True, help="Path to dataset json.")
    parser.add_argument("--sample-index", type=int, required=True, help="Sample index in dataset.")
    parser.add_argument(
        "--answer-text",
        default=None,
        help="Model output or final answer text. If omitted, will read from --results-json.",
    )
    parser.add_argument(
        "--results-json",
        default=None,
        help="Optional results.json generated by eval script. If set, uses that sample's raw output.",
    )
    return parser.parse_args()


def parse_goal(text):
    match = GOAL_PATTERN.search(text)
    if match:
        return int(match.group(1)), int(match.group(2))
    return None


def parse_start(text):
    match = START_PATTERN.search(text)
    if match:
        return int(match.group(1)), int(match.group(2))
    return (0, 0)


def parse_holes(text):
    match = HOLES_LINE_PATTERN.search(text)
    if not match:
        return set()
    return {tuple(map(int, xy)) for xy in COORD_PATTERN.findall(match.group(1))}


def clean_output(text):
    text = text.replace("<|grid_pad|>", " ")
    text = re.sub(r"<\|[^>]+\|>", " ", text)
    text = text.replace("\ufffd", " ")
    text = re.sub(r" {2,}", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def normalize_path_text(text):
    moves = re.findall(r"go\s+(?:left|right|up|down)", text.lower())
    if not moves:
        return None
    return " -> ".join(move.strip() for move in moves)


def extract_answer(text):
    text = clean_output(text)
    match = ANSWER_PATTERN.search(text)
    if match:
        answer = normalize_path_text(match.group(1))
        if answer:
            return answer
    candidates = PATH_PATTERN.findall(text)
    if candidates:
        candidates.sort(key=len, reverse=True)
        return normalize_path_text(candidates[0])
    return None


def parse_moves(text):
    answer = extract_answer(text) or text
    moves = [m.lower() for m in MOVE_PATTERN.findall(answer)]
    return answer, moves


def apply_move(position, move):
    row, col = position
    if move == "up":
        return row - 1, col
    if move == "down":
        return row + 1, col
    if move == "left":
        return row, col - 1
    if move == "right":
        return row, col + 1
    raise ValueError(f"Unsupported move: {move}")


def infer_bounds(start, goal, holes):
    coords = [start, goal, *holes]
    max_row = max(r for r, _ in coords)
    max_col = max(c for _, c in coords)
    return max_row + 1, max_col + 1


def main():
    args = parse_args()

    with open(args.dataset_path) as f:
        dataset = json.load(f)
    sample = dataset[args.sample_index]
    reference = sample["conversations"][-1]["value"]

    raw_text = args.answer_text
    if raw_text is None and args.results_json:
        with open(args.results_json) as f:
            results = json.load(f)
        matched = next((x for x in results if x["sample_index"] == args.sample_index), None)
        if matched is None:
            raise ValueError(f"Sample index {args.sample_index} not found in results json")
        raw_text = matched.get("raw_output") or matched.get("clean_output") or matched.get("extracted_answer")

    if not raw_text:
        raise ValueError("Provide --answer-text or --results-json")

    start = parse_start(reference)
    goal = parse_goal(reference)
    if goal is None:
        raise ValueError("Could not parse goal coordinates from sample reference")
    holes = parse_holes(reference)
    rows, cols = infer_bounds(start, goal, holes)

    normalized_answer, moves = parse_moves(raw_text)
    position = start
    trajectory = [position]
    status = "in_progress"
    reason = ""

    for step_id, move in enumerate(moves, start=1):
        next_pos = apply_move(position, move)
        trajectory.append(next_pos)

        if not (0 <= next_pos[0] < rows and 0 <= next_pos[1] < cols):
            status = "out_of_bounds"
            reason = f"step {step_id}: {move} -> {next_pos}"
            position = next_pos
            break

        if next_pos in holes:
            status = "fell_into_hole"
            reason = f"step {step_id}: {move} -> {next_pos}"
            position = next_pos
            break

        position = next_pos
        if position == goal:
            status = "reached_goal"
            reason = f"step {step_id}: {move} -> {position}"
            break

    if status == "in_progress":
        if position == goal:
            status = "reached_goal"
            reason = f"finished at {position}"
        else:
            status = "stopped_before_goal"
            reason = f"finished at {position}, goal is {goal}"

    print(f"sample_index: {args.sample_index}")
    print(f"start: {start}")
    print(f"goal: {goal}")
    print(f"holes: {sorted(holes)}")
    print(f"grid_size: {rows} x {cols}")
    print(f"normalized_answer: {normalized_answer}")
    print(f"moves: {moves}")
    print(f"trajectory: {trajectory}")
    print(f"status: {status}")
    print(f"reason: {reason}")


if __name__ == "__main__":
    main()
